### ISSUE TITLE
Is this project accepting contributors?

### ISSUE THREAD

**Issue by mlolson** [seattleflu/id3c#133]
Happy to help if possible.

**Comment by kairstenfay** [comment]
Hi @mlolson! Thanks for reaching out. 

I'm not sure we actually have tasks right now that aren't intimately tied to Seattle Flu Study data. Perhaps a couple months down the road, post pandemic, we'd be able to scope out some core ID3C tasks and onboard volunteer contributors.

Meanwhile, http://nextstrain.org (https://github.com/nextstrain/) is accepting contributors.  

Cheers!

**Comment by mlolson** [comment]
Got it, I just saw this one on the UW jobs site and was curious. Thanks!
